
//PRODUCT


###

GET http://localhost:8000/product

###

GET http://localhost:8000/product/5



###

POST http://localhost:8000/product
content-type: application/json

{
    "name":"Nikee",
    "slug":"gutalaa"
    
}

###

DELETE http://localhost:8000/product/1cM0mBA6-CIMmN6adZ1bz

###

PUT http://localhost:8000/product/SuWHjqQu6MeysNx2hExEf
content-type: application/json

{
    "name":"Shopdsadsa",
    "slug":"history123333dsadsa"
 
}

###
//USER

GET http://localhost:8000/users

###

GET http://localhost:8000/users



###

POST http://localhost:8000/users
content-type: application/json

{
    "firstName":"Temuulen",
    "lastName": "daride",
    "birthDate" : "1998-07-11",
    "email": "temuulennn.m@pinecone.mn",
    "phone": "89898989",
    "password": "",
    "imageUrl": ""
}

###

DELETE http://localhost:8000/users/0Tc3GwlqkRMJ574WX0wt2

###

PUT http://localhost:8000/users/Yv5DpMq_wTDku1OuXxTN8
content-type: application/json

{
    "firstName": "daaaaaaas",
    "lastName": "dsaaaa",
    "birthDate": "1235-07-10",
    "email": "dsa.m@pinecone.mn",
    "emailConfirmed": 0,
    "phone": 1112211,
    "phoneConfirmed": 0,
    "password": "",
    "imageUrl": "",
    "isAdmin": 0,
    "created": null,
    "updated": null,
    "updatedAt": null
}


###
//Category

GET http://localhost:8000/category

###

GET http://localhost:8000/category



###

POST http://localhost:8000/category
content-type: application/json

{
    "name":"Nike",
    "slug":"t-shirt",
    "productCount":"0"

}

###

DELETE http://localhost:8000/category/CZGTJ5z8KnhKQ1q9vTx8X

###

PUT http://localhost:8000/category/mlkkXvnd0a7xigbEMwPib
content-type: application/json

{
    "name": "Puma",
    "slug": "tt-shirtt",
    "productCount": 43,
    "parent_id": null,
    "createdAt": "",
    "updated": null,
    "updatedAt": null
}

###

//ProductImage


GET http://localhost:8000/productImage

###

GET http://localhost:8000/category



###

POST http://localhost:8000/productImage
content-type: application/json

{
    "imageUrl":"google.com/awatipool-query"

}

###

DELETE http://localhost:8000/productImage/jkQi1KnrgDzWXUdBxxVUO

###

PUT http://localhost:8000/productImage/m1bmPHNOr9nyCjp5j-Fw6
content-type: application/json

{
    "imageUrl":"youtube.com/awatipool-query"
}

###

//ProductReview


GET http://localhost:8000/productReview

###

GET http://localhost:8000/category



###

POST http://localhost:8000/productReview
content-type: application/json

{
    "rating":""
}

###

DELETE http://localhost:8000/productReview/jkQi1KnrgDzWXUdBxxVUO

###

PUT http://localhost:8000/productReview/m1bmPHNOr9nyCjp5j-Fw6
content-type: application/json

{
    "rating":"youtube.com/awatipool-query"
}