GET http://localhost:8000/categories

###
GET http://localhost:8000/categories/id
content-type: application/json

{
    "id":15
}

###

POST http://localhost:8000/categories
content-type: application/json

{
    "name":"Technology",
    "slug":"tech12",
    "imgUrl":""
}

###

DELETE http://localhost:8000/categories
content-type: application/json

{
    "id":"17"
}

###

PUT http://localhost:8000/categories
content-type: application/json

{
    "id":"15",
    "name":"Shop23",
    "slug":"shop22",
    "imgUrl":""
}